# Change these first
owner: machankura # Your GitHub organization or username, where this repository lives
repo: machankura.status # The name of this repository

sites:
  - name: Machankura Home Page
    url: $MACHANKURA_WEB_PAGE_HTTP_URL
  - name: Machankura USSD Service
    url: $MACHANKURA_USSD_SERVICE_HTTP_ENDPOINT
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Machankura Whatsapp Service
    url: $MACHANKURA_WHATSAPP_SERVICE_HTTP_ENDPOINT
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Machankura Web Service
    url: $MACHANKURA_WEB_SERVICE_HTTP_ENDPOINT
    expectedStatusCodes:
      - 200
      - 201
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.machankura.com
  baseUrl: /machankura.status
  logoUrl: $MACHANKURA_LOGO_URL
  name: Machankura Status Page
  introTitle: "Status page for Machankura services."
  introMessage: This is a status page that tracks **Machankura** services. [**Create a Machankura account**](https://8333.mobi)
  navbar:
    - title: Status
      href: /
    - title: Machankura
      href: https://machankura.com

  user-agent: ceboMakeleni

  theme: ocean
  favicon: $MACHANKURA_LOGO_URL
  faviconSvg: $MACHANKURA_LOGO_URL

  assignees:
  - ceboMakeleni
  - kngako
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
